/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author anant
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnViewAllVehicles = new javax.swing.JButton();
        btnSearchVehicle = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeleteVehicle = new javax.swing.JButton();
        btnRentVehicle = new javax.swing.JButton();
        btnReturnVehicle = new javax.swing.JButton();
        btnViewRentedVehicles = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add Vehicle ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnViewAllVehicles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewAllVehicles.setText("View All Vehicle ");
        btnViewAllVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllVehiclesActionPerformed(evt);
            }
        });

        btnSearchVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchVehicle.setText("Search Vehicle By Reg");
        btnSearchVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVehicleActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update Vehicle ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDeleteVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteVehicle.setText("Delete Vehicle ");
        btnDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVehicleActionPerformed(evt);
            }
        });

        btnRentVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRentVehicle.setText("Rent Vehicle ");
        btnRentVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentVehicleActionPerformed(evt);
            }
        });

        btnReturnVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturnVehicle.setText("Return Vehicle ");
        btnReturnVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnVehicleActionPerformed(evt);
            }
        });

        btnViewRentedVehicles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewRentedVehicles.setText("View Rental Vehicle ");
        btnViewRentedVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRentedVehiclesActionPerformed(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReturnVehicle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewRentedVehicles)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addComponent(btnSearchVehicle)
                            .addComponent(btnDeleteVehicle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAllVehicles)
                            .addComponent(btnUpdate)
                            .addComponent(btnRentVehicle))
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Logout)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnViewAllVehicles))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchVehicle)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteVehicle)
                    .addComponent(btnRentVehicle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnVehicle)
                    .addComponent(btnViewRentedVehicles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true); // Wapas Login Screen dikhao
        this.dispose(); // Dashboard close karo
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
            new AddVehicleForm().setVisible(true);

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnViewAllVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllVehiclesActionPerformed
        new ViewVehiclesForm().setVisible(true);
    }//GEN-LAST:event_btnViewAllVehiclesActionPerformed

    private void btnSearchVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVehicleActionPerformed
            new SearchVehicleForm().setVisible(true);

    }//GEN-LAST:event_btnSearchVehicleActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        new UpdateVehicleForm().setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVehicleActionPerformed
        new DeleteVehicleForm().setVisible(true);
    }//GEN-LAST:event_btnDeleteVehicleActionPerformed

    private void btnRentVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentVehicleActionPerformed
        new RentVehicleForm().setVisible(true);
    }//GEN-LAST:event_btnRentVehicleActionPerformed

    private void btnReturnVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnVehicleActionPerformed
        new ReturnVehicleForm().setVisible(true);
    }//GEN-LAST:event_btnReturnVehicleActionPerformed

    private void btnViewRentedVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRentedVehiclesActionPerformed
        new ViewRentedVehiclesForm().setVisible(true);
    }//GEN-LAST:event_btnViewRentedVehiclesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteVehicle;
    private javax.swing.JButton btnRentVehicle;
    private javax.swing.JButton btnReturnVehicle;
    private javax.swing.JButton btnSearchVehicle;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewAllVehicles;
    private javax.swing.JButton btnViewRentedVehicles;
    // End of variables declaration//GEN-END:variables
}
